#!/bin/sh /etc/rc.common
# OOB witness: reachability probes, paging, red logo LED on failure
START=99
USE_PROCD=1
start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/velo540-witness
	procd_set_param respawn 3600 10 0
	procd_close_instance
}
