#!/bin/sh /etc/rc.common
# Software fan curve for the EMC2104 (see /usr/sbin/velo540-fand).
# Runs after velo540-switch has set the PCA9557 FORCE_PWM/FORCE_12V pins.
START=20
USE_PROCD=1
start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/velo540-fand
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
stop_service() {
	i2cset -y 9 0x2f 0x40 0xff 2>/dev/null	# fail safe: full speed when unmanaged
}
